# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

target 'WKReactNativeLearn' do

pod 'React', '~> 0.13.0-rc'

pod 'React/RCTText', '~> 0.13.0-rc'

end
